### ISSUE TITLE
Did not work with me?

### ISSUE THREAD

**Issue by eArabic** [phhpro/easy-comments#1] opened 2017-12-30 08:05 UTC
Hello my friend
Thank you very much for sharing this script, but I could not make it work and did not know how to use it.
Is it possible to put an example or explain how to use I am a newbie programming.
thank you very much

**Comment by phhpro** [comment] 2017-12-30 19:05
Hello there, and thanks for the feedback. Turns out I made a boo last time around, sorry. Just pushed a fresh update and all seems to be back to normal on local and remote dev. As per your request I've added a minimal demo at phclaus.com/demo/easy-comments. Please fetch a copy of the latest build and let me know if you need further assistance. By the way, Happy New Year 2018 :)

**Comment by eArabic** [comment] 2018-01-01 10:28
Hello dear friend
Thanks so much for the updates.
I still do not work and I do not know what the reason is.
This is a test of the site:
[easy-comments](http://bok.altervista.org/easy-comments/)

**Comment by phhpro** [comment] 2018-01-01 11:29
That's odd. I see you are using 20180101. The latest patch got live some 2 hours ago. Had a look at the URL you provided. The script loads fine, posts without error, but apparently nothings gets written to the data file.

In theory, the script tries to detect permissions and spits out an error, but I've noticed that that doesn't always work. I had a similar situation on one of my dev boxes. The solution was to chmod the whole folder from my uid to www-data and gant write permissions to the files therein.

I suggest you open the site in your FTP client and have a look at the current permissions, just to be sure. Folders are usually 0755 and files 0644. Which PHP version do you have? Did you edit the config section? If so, please post a snippet of what's between begin and end of user config.

Regards,
P H Claus

**Comment by eArabic** [comment] 2018-01-01 11:50
Dear Friend
Thank you very much for your response and for helping resolve the issue.
I will try another hosting.
best regards


![aaa](https://user-images.githubusercontent.com/24383546/34467440-f891b2ba-ef02-11e7-90c6-0853af344d99.png)
![333](https://user-images.githubusercontent.com/24383546/34467441-f8c52c26-ef02-11e7-8894-e70a2a4f71b6.png)

**Comment by phhpro** [comment] 2018-01-01 12:04
Sorry, I'm not that fluent in Arabic :) 755 is the folder and good, but permissions of the script appear to be 0600, which is rather restrictive. Should work though. PHP 5.6 is a little old but still perfectly valid. no problem there.

Anyway, I've played around a bit and just uploaded another update. Added two chmod conditions to fix data and log file permissions. Tried on dev with a virgin install (neither data, nor log file exist) and works. Thanks for bearing with me :)

**Comment by phhpro** [comment] 2018-01-01 12:16
Forgot to mention, the latest has also gotten a new variable eco_path to set the proper value of $_SERVER['DOCUMENT_ROOT'] because that has the potential to return a wrong value. If you don't know your path you can always try the global. Haven't run phpinfo() in a while but it used to print the value.

**Comment by eArabic** [comment] 2018-01-01 13:10
Dear Friend
Thank you so much.
It also did not work.

PHP_SELF	/easy-comments/info.php
SERVER_NAME	bok.altervista.org
SERVER_SOFTWARE	Apache
DOCUMENT_ROOT	/var/www/html
HTTP_HOST	bok.altervista.org
SCRIPT_FILENAME	/membri/bok/easy-comments/info.php
SCRIPT_NAME	/easy-comments/info.php
REQUEST_URI	/easy-comments/info.php
ORIG_PATH_INFO	/easy-comments/info.php

**Comment by phhpro** [comment] 2018-01-01 13:20
There you have it. That /var/www/html may well be the default server's environment. I've had lots of fun with broken env's in the past. Guess what, I even have the same on local dev, so while I can use the server global on the live site,I still need to edit the path on local. Unless I do that, I get exactly the same effect like you.

Fetch 20180101.7 and then edit $eco_path to hold the proper value. Try $eco_path = "/membrik/bok"; o begin with.

**Comment by phhpro** [comment] 2018-01-01 13:22
arg, that's /membri/bok ...

**Comment by phhpro** [comment] 2018-01-01 13:24
Um, if that doesn't work, check your control panel where it says home folder or alike

**Comment by eArabic** [comment] 2018-01-01 13:29
Thank you so much
Now it is working, very excellent problem has been solved.
Thank you so much

**Comment by phhpro** [comment] 2018-01-01 13:30
OK, had look around. Seems I was right about var/www. Check the response at  http://forum.en.altervista.org/services/2036-php-document-root.html -- similar issue

**Comment by phhpro** [comment] 2018-01-01 13:31
Glad to hear you've got it solved. Don't hesitate to post back anytime you're bumping into another hole :)

**Comment by eArabic** [comment] 2018-01-01 13:32
Thank you very much my dear friend, I was glad to meet you.

**Comment by phhpro** [comment] 2018-01-01 13:40
No problem. I just went back to the site and tried myself. You should edit your tokens before making the script public. Also check the rest of the config, like mail settings. Defaults are 0 (off). To get notified on new posts that needs to read 1 (on).

However, for mail to pass, the address (default: info) and header format must match your host's requirements. You probably don't have access to php mail() anyway. Try and error :)

**Comment by eArabic** [comment] 2018-01-01 14:03
Thank you so much
I did not understand what to modify
And how to enter the Adman account to respond to comments 
(You can post admin replies by entering the values of $eco_apfx and $eco_asfx)

**Comment by phhpro** [comment] 2018-01-01 14:24
Line #70 ($eco_apfx) sets the admin prefix and line #78 ($eco_list) sets the query token to list the master log file. A little further up, line #66 ($eco_mail) sets the mail account. This is used to send and receive, so it obviously must exist.

The only part you'll need to change there is "info". For example, if you have an account like bok@altervista.com, you'd change "info" to "bok". Just above on line #65 change the 0 to read 1. In principle that's all there is. You should now receive a brief mail whenever someone posts a new comment so you don't have to search around yourself.

Once you know that mail is working, you may want to consider switching from unrestricted to moderated posting to check the post before you decide whether it's apropiate or not to be published. You can then publish the comment directly from the notification mail - if mail works.

Regarding the master log file, and how to view it: you simply append the value of $eco_list to the script's URL and hit Enter, e.g. if you set $eco_list = "keep-me-posted"; the URL would look like http://yoursite.com/easy-comments/?keep-me-posted

Just think of something more or less obscure to limit spoofing. Ah, and you can of course totally exclude (ban) certain names (or fragments) from being used altogether. That's done in resticted.php

**Comment by eArabic** [comment] 2018-01-01 16:47
Dear Friend
Thank you very much for this excellent script
Please add a feature to include an image or file with the comment.

**Comment by eArabic** [comment] 2018-01-01 16:53
How to make a saved files: _comments.html
Inside a subfolder, for example: Datahtml

**Comment by phhpro** [comment] 2018-01-01 17:06
The script automatically creates filename.ext_comments.html in the same folder, e.g if you reference the script in /foo/bar/batz.php the script creates /foo/bar/batz.php_comments.html

Just make sure to keep session_start() and ob_flush() at the very top of any page for which you want to enable commenting. At the very top as in lines #2 and #3 right after the <?php opening tag. Refer to the demo index.php and just copy/paste or put it in your global header -- at the very top. Else, the script is bound to make a major boo...

Actually I had thought about external stuff like images, etc. Writing the source is little magic, but the technical requirements are beyond most free hosting providers. Given time and muse I might consider it. Hm, PHP Easy Comments Premium. I like that. Haha ;)

**Comment by phhpro** [comment] 2018-01-01 17:07
Ahem, ob_start of course

**Comment by eArabic** [comment] 2018-01-01 18:13
Thank you so much
Beautiful fast fast and excellent
I'm a beginner I do not know by programming Look at:
http://bok.altervista.org/easy-comments/create.php
Go to page: phhpro
A nice idea to share discussions independently with friends ...
Please add some features such as inserting an image or file they are very important.

**Comment by eArabic** [comment] 2018-01-01 19:13
Hello
I did not know how to use this:
//** Admin prefix and suffix
$eco_apfx = "myweb";
$eco_asfx = "Root";
An example of how it works is possible
I did not know how to write in the name of root
Possible explain how I am a beginner and thank you very much.

**Comment by eArabic** [comment] 2018-01-01 22:32
Hello my friend
There is a problem with writing the Arabic name, when the Latin name is disabled; the Arabic is working, and the Latin does not work
How to make everyone work.
thank you very much

**Comment by phhpro** [comment] 2018-01-02 03:47
The script has a setting to allow Latin only, but that's definitely not what you want because it would obviously deny any non-Latin scripts, like Arabic and Asian. Else, the script accepts pretty much everything everything; including Klingon if you dare :) Just tested this on the latest demo at phclaus.com/demo/easy-comments

To post as root, you enter the values of $eco_apfx and $eco_asfx into the name field, without spaces. Considering your previous post you would thus enter mywebRoot

I'll try to have a look at the Create link, though I'm not sure I understand the purposes. This script is meant to add inline comments to existing pages. It is by no means a 'blog', though one could easily expand the code to add extra features. YMMV

**Comment by eArabic** [comment] 2018-01-02 05:28
Hello dear friend
Thank you very much for continuous updates.
There is a problem when entering an Arabic name  : العربية
Please resolve this issue.

![aaaa](https://user-images.githubusercontent.com/24383546/34474912-cb992696-ef96-11e7-8722-dbf6e3eccb14.png)

**Comment by eArabic** [comment] 2018-01-02 06:10
Please add the option to disable or enable verification
$eco_code = 0; 
$eco_cmin = 1;
$eco_cmax =9;

Where can I control and approve comments, and not display them directly?
It is nice to have the option of displaying comments directly without review; such as the current situation.
And that there is an option to review the comments before posting, allowing and approving them.

**Comment by phhpro** [comment] 2018-01-02 06:37
I should get some sleep once in a while :) Was thinking you were talking about the textarea when in fact it was the name field. That's already fixed in the latest build. Had been on my list but somehow kept slipping down. Done.

The control code, aka CAPTCHA, is actually a security feature to limit SPAM. You wouldn't like tons of bots or human dummies to keep auto-filling the form with crap, would you? That said, I don't intend to make it optional. If you still want to remove it and knowingly expose your site to all sorts of evil, you'll have to jump into the script and either comment or remove the corresponding mark-up from line #425 to line #433.

To turn on moderator mode you'll need to set $eco_mapp = 1 and $eco_note = 1 Just make sure your mail settings work as expected. Probably best to just turn on notifications per $eco_note = 1 and post an entry. If your mail works, you should receive a mail more or less instantly. Depending your server there may a brief lag, maybe a few minutes.

Before you go cursing over the script, doule-check by sending a test mail from your server to someone else and ask for a reply. If that goes through but the script fails to send, you may need to tweak the header, in particular the Reply-To format is a bit odd on some hosts.

**Comment by eArabic** [comment] 2018-01-02 06:49
Dear Friend
Thank you very much for your help.
I am very happy with you, thank you for quick responses, update, and help.
**Please add the Pagination feature to show a specific number of comments per page, if many comments prefer Pagination.**

**Comment by phhpro** [comment] 2018-01-02 07:21
Something along the lines of pagination has been on my list for a while. I'll probably give it another thought in between flights. For the time being there are other priorities, like having meeting a client in just a few hours to finalise one of the current projects before preparing my travel bag.

**Comment by phhpro** [comment] 2018-01-02 08:03
Very well, the control code feature is optional as of 20180102.3 per $eco_ctrl = 0

**Comment by eArabic** [comment] 2018-01-02 08:59
Thank you so much my dear friend

**Comment by phhpro** [comment] 2018-01-02 09:07
Any luck with mail? But wait, before you go trying, let me ask a silly question: You do have a proper mail account on that host? I've never tried altervista. Do they have a control panel? Even if you have mail enabled, you probably still need to create an account first. In case you don't have any other way to test sending/receiving drop me a line. I have a plenty of mails all over the place :)

**Comment by phhpro** [comment] 2018-01-02 09:10
Almost forgot. Since I decided to add multi-language support, would you be interested to contribute an Arabic translation? It's really small and shouldn't take much more than perhaps 10 minutes for a native speaker.

**Comment by eArabic** [comment] 2018-01-02 11:47
Thank you so much my dear friend
They have an email, and I do not have any problems with mail delivery settings, most of which work for me automatically.
They have a control panel as well as an ftp account
I did not adjust my mail settings to receive messages.
I place a Gmail and send messages to  Gmail.

![10](https://user-images.githubusercontent.com/24383546/34482660-74399c62-efca-11e7-8dcc-600b58d55fc4.png)
![9](https://user-images.githubusercontent.com/24383546/34482661-746a7fa8-efca-11e7-9221-022faad1caf1.png)

![eee](https://user-images.githubusercontent.com/24383546/34482868-d932c23c-efcb-11e7-9409-ef5b2ceb8d30.png)
![default](https://user-images.githubusercontent.com/24383546/34482869-d9554078-efcb-11e7-9ced-f9de67ad946e.png)



[lang (1).zip](https://github.com/phhpro/easy-comments/files/1597443/lang.1.zip)

**Comment by eArabic** [comment] 2018-01-02 11:51
```

//** Init array
$eco_lang = array();

//** Strings
$eco_lang['miss_log']     = "ملف سجل مفقود ";
$eco_lang['mod_flag']     = "وضع المشرف هو نشط ولكن يتم تعطيل الإخطارات ";
$eco_lang['chk_settings'] = "يرجى التحقق من الإعدادات لتصحيح الخطأ ";
$eco_lang['fix_error']    = "سيتم تعطيل النص البرمجي حتى يتم إصلاح الخطأ";
$eco_lang['invalid_char'] = "سيتم تعطيل النص البرمجي حتى يتم إصلاح الخطأ ";
$eco_lang['invalid_code'] = "رمز التحكم غير صالح ";
$eco_lang['miss_text']    = "لا يمكن نشر تعليق فارغ ";
$eco_lang['only_latin']   = "الأحرف اللاتينية فقط المسموح بها ";
$eco_lang['view_item']    = "انقر هنا لعرض هذا البند";
$eco_lang['mod_wait']     = "شكرا لكم. تعليقك ينتظر الموافقة عليه ";
$eco_lang['add_new']      = "انقر هنا لإضافة تعليق جديد";
$eco_lang['add_comment']  = "أضف تعليق";
$eco_lang['be_first']     = "لا تعليقات حتى الآن. كن أول من يشارك أفكاره ";
$eco_lang['name']         = "الإسم";
$eco_lang['az']           = "A - Z";
$eco_lang['only']         = "فقط";
$eco_lang['type_name']    = "اكتب هنا لإدخال اسمك أو تركه فارغا لنشر مجهول";
$eco_lang['text']         = "نص";
$eco_lang['type_text']    = "اكتب هنا لإدخال نص تعليقك";
$eco_lang['code']         = "كود";
$eco_lang['type_code']    = "اكتب هنا لإدخال رمز التحكم";
$eco_lang['post']         = "مشاركة";
$eco_lang['type_post']    = "اضغط هنا لنشر تعليقك";
$eco_lang['post_again']   = "شكرا لكم. يمكنك نشر مرة أخرى في";
$eco_lang['seconds']      = "ثواني";
$eco_lang['man_refresh']  = "حدث هذه الصفحة لتحديث الموقت يدويا.";
$eco_lang['mod_require']  = "تتطلب المشاركات الجديدة موافقة المشرف";
$eco_lang['be_polite']    = "كن مهذبا والامتناع عن لغة سيئة";
$eco_lang['get_copy']     = "انقر هنا للحصول على نسخة مجانية من";
$eco_lang['powered_by']   = "مشغل بواسطة";
$eco_lang['char_rem']     = "الأحرف المتبقية";
$eco_lang['name_rest']    = "يتم تقييد جزء أو كل الاسم المحدد!";

```

**Comment by eArabic** [comment] 2018-01-02 11:59
Thank you so much
The name is accepted in Arabic.
Please enable the Add Picture or File feature
[easy](http://bok.altervista.org/easy/)

**Comment by eArabic** [comment] 2018-01-02 13:24
What does this error mean continuously ...
![000000](https://user-images.githubusercontent.com/24383546/34484997-62150436-efd9-11e7-98bb-f4ae022ba78d.png)

**Comment by phhpro** [comment] 2018-01-02 18:26
Thinking a little more, about how limited language icons really are, 20180201.5 reverts to plain text identifiers. That apart, your lang.zip contained the German language file. You probably zipped up the wrong file? Never mind, I have added a machine translation you can review at the demo.

Mail: I'm afraid having to disappoint you, but I didn't get anything. Where did you send it to? Besides, the code you posted above is certainly not part of the script. In fact, I doubt it would send anything. 

$body, $from_mail, $from_name, $replyto are sort of declared but not used, and $header doesn't even exist. Wherever you got that thingie from must be a very obscure place indeed.

Ah, yes, the type error. That's perfectly save to ignore and voids itself upon posting anyway. It's caused by building the mark-up via PHP echo. Therefore JS fails to see it and promptly claims the ID is null or undefined. Nothing to worry about.

**Comment by phhpro** [comment] 2018-01-02 18:33
Um, had a second glance at the image. If that's the sender's address (top right) I'm not surprised it got bounced. Name servers neither send nor receive mail. But who knows. Free hosts have a long tradition of exotic setups. Try sending something to one of my public mails at phhpro@gmail.com

**Comment by eArabic** [comment] 2018-01-02 21:08
Thank you so much my dear friend
I apologize if there is any error in the replies, because I am translating the machine and I understand wrongly, I do not know English.
Thank you very much for adding Arabic, translation is good.
There was more than one post already there is a link to the German translation error and this link from my post is the correct link:
https://github.com/phhpro/easy-comments/files/1597443/lang.1.zip

![8888](https://user-images.githubusercontent.com/24383546/34500007-f06786f6-f019-11e7-9843-1b87f7bba841.png)

The translation code has been placed in the previous post
However the machine translation is correct and good.
Thank you so much my dear friend

**Comment by phhpro** [comment] 2018-01-02 21:17
Curious, did you get my reply?

**Comment by eArabic** [comment] 2018-01-02 21:23
These have some required features
   - Admin panel Simple.
   - Search.
   - Images and files upload.
   - Pagination.
   - sticky comment Top Page .
   - Special fields.
   - Disable comments from a specific page (disable list and allow list).
   -Star Ratings
   And more

**Comment by eArabic** [comment] 2018-01-02 21:30
sorry, I did not understand
Did not show the last reply you had
[PDF.pdf](https://github.com/phhpro/easy-comments/files/1598736/PDF.pdf)

**Comment by phhpro** [comment] 2018-01-02 21:51
I suppose that's your wishlist for next year's christmas :)

Admin panel: To administer what? The script's primary purpose is to provide simple inline comments with minimal requirements, aka set it and forget it. Adding extra features and building stuff around the original concept is quite possible but part of the user.

Search: There are tons of search scripts all over the web. Most hosts; even free ones; have more or less useful gadgets ready to install. Check your control panel. Once you have found one you like, just edit the script to add the required mark-up where you want the feature to appear. Careful though! Messing with the sources might well break things. Always make a copy in a different location to test.

Images and files: Like I said before, it's on my mind; just not now.

Pagination: see above

Sticky top: That would be a header. Just create the mark-up you want and include the file before the script. The same is true for a footer, sidebar, etc.

Special fields: Absolutely no idea what that would be???

Disable comments on specific pages: Simply don't reference the script in files for which you don't want comments. Done.

Rating: Comments usually come in the form of feedback to past or future events. I don't see the point in rating someone elses opinion. Most people would probably just say something like, 'wow, great post, totally agree' or 'ugh, what a load of crap, get lost' and that's all the rating it needs. Works quite nicely without fancy icons.

And more: Now that's an absolute must have :) Could I have some?

**Comment by phhpro** [comment] 2018-01-02 21:56
Reply: I was referring to email.

**Comment by eArabic** [comment] 2018-01-02 22:13
Hello dear friend
You are right to the previous comment, but the goal was to add features is learning php language
For mail I have not received any response, send any test message to this mail: **bok@altervista.org**
For Script: easy-comments
When I activate the mail feature (Send notifications) I do not receive any message with it working later one or two times and then stopped.
The mail I have is working.
![55555](https://user-images.githubusercontent.com/24383546/34502146-3babdd5c-f023-11e7-8299-d3a22cd01f5b.png)

**Comment by phhpro** [comment] 2018-01-02 22:26
Edit the script and scroll down to the user config section. Find these variables and edit as shown.

$eco_note = 1;
$eco_mail = "bok@" . $_SERVER['HTTP_HOST'];

If that doesn't get you notified you should first of all contact your host and ask if you can actually use php mail() to send mails. Anything not beginning with YES, you can means, well, NO, you cannot :(

**Comment by eArabic** [comment] 2018-01-02 22:32
Thank you very much Now it works very well, you have modified the code to:

![7777](https://user-images.githubusercontent.com/24383546/34502732-e8a75e94-f025-11e7-808c-9da24510364c.png)
![00000](https://user-images.githubusercontent.com/24383546/34502733-e8cd28d6-f025-11e7-8e72-c9b92aaaa400.png)

**Comment by eArabic** [comment] 2018-01-02 22:36
What is the second step? How do I agree and accept the comment after it arrives for mail?

**Comment by phhpro** [comment] 2018-01-02 22:36
Tada (insert favourite jingle here) 🥇

**Comment by phhpro** [comment] 2018-01-02 23:17
Caught an error new in PHP 7 when doing maths and running into non-numeric issues. Good news, that one's fixed already by prefixing the values with (int) -- The bad news however is, that I also found a stacking error which prevents the mod-link from working like before. I'm on it and will get back to you as soon as. However, it's already rather late, so that'll be sometime tomorrow. Please keep $eco_mapp = 0 for the time being.

**Comment by phhpro** [comment] 2018-01-03 00:00
Luck you. Bit of late-night tweaking around, all good. Tested on live site and mod link works again. Patch already in repo. Current latest is 20180103

**Comment by eArabic** [comment] 2018-01-03 00:28
Thank you so much, so excellent it is up to the post approval link.
But there is a problem after clicking the link:
![qqxx](https://user-images.githubusercontent.com/24383546/34505394-18b3637a-f036-11e7-9726-719458f82826.png)

**Comment by eArabic** [comment] 2018-01-03 00:33
The problem is in the title of the link
**http://bok.altervista.org/easy/?eco_data=/membri/bok//comments/easy/index.php_comments.html**

**Comment by eArabic** [comment] 2018-01-03 00:45
I tried manually editing the link.
**The wrong link to mail is:**

http://bok.altervista.org/easy/?eco_data=/membri/bok//comments/easy/index.php_comments.html&eco_post=2020202020202020202020203c6469762069643d65636f5f32303138303130335f3030343032325f33372e3130342e3232342e3137345f78787878787878787878787878787878787878787878787820636c6173733d65636f5f6974656d3e323031382d30312d30332030303a34303a323220787878787878787878787878787878787878787878787878202420787878787878787878787878787878787878787878787878787878787878783c2f6469763e0a&eco_link=comments/easy

**Manually modified link is:**

http://bok.altervista.org/comments/easy/?eco_data=index.php_comments.html&eco_post=2020202020202020202020203c6469762069643d65636f5f32303138303130335f3030343032325f33372e3130342e3232342e3137345f78787878787878787878787878787878787878787878787820636c6173733d65636f5f6974656d3e323031382d30312d30332030303a34303a323220787878787878787878787878787878787878787878787878202420787878787878787878787878787878787878787878787878787878787878783c2f6469763e0a&eco_link=

The manual link works perfectly well but how to solve this problem

**Comment by phhpro** [comment] 2018-01-03 01:24
First, you seem to have a trailing slash at the end of $eco_path -- Please remove that.

I'm a bit puzzled. The eco_link param tells the script where to go to after publishing. Perhaps another slash issue with $eco_fold? Looking again I see you have two locations for the same script. The URL points to /easy but $eco_data reads /comments/easy

So where do keep the script? in /easy, or in /comments/easy?

I believe your config should look like:

$eco_path = "/membri/bok";
$eco_fold = "/easy/";

Again
$eco_path: NO trailing slash
$eco_fold: leading and trailing slash

**Comment by phhpro** [comment] 2018-01-03 01:27
by the way, the 'no language file' warning is already fixed in latest, as was the ghosted timer and some minor cosmetics

**Comment by eArabic** [comment] 2018-01-03 05:41
Thank you very much, very excellent that it works properly.
I was mistaken I had put a slash and when I deleted it it worked very excellently.

_So where do keep the script? in /easy, or in /comments/easy?_
Actually you're right I have more than one copy.
Where I do test and experiment.

Thank you very much for the update and for help.

**Comment by phhpro** [comment] 2018-01-03 15:03
Splendid. I take it from there all is good, so I'll close this. You are very welcome to open a new ticket whenever you need further assistance. Have fun experimenting and check back once in a while to grab the latest. Regards.

**Closed by phhpro** 2018-01-03 15:04 UTC
